services:
  api-gateway:
    environment:
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: ${PETCLINIC_SAMPLING_PROBABILITY:-1.0}

  customers-service:
    environment:
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: ${PETCLINIC_SAMPLING_PROBABILITY:-1.0}

  visits-service:
    environment:
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: ${PETCLINIC_SAMPLING_PROBABILITY:-1.0}

  vets-service:
    environment:
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: ${PETCLINIC_SAMPLING_PROBABILITY:-1.0}
